if SERVER then
	include("gitrc.lua")
	
	resource.AddSingleFile("materials/models/condom/condom_texture.vmt")
	resource.AddSingleFile("materials/models/condom/condom_texture.vtf")
	resource.AddSingleFile("models/condom/condom.dx80.vtx")
	resource.AddSingleFile("models/condom/condom.dx90.vtx")
	resource.AddSingleFile("models/condom/condom.mdl")
	resource.AddSingleFile("models/condom/condom.phy")
	resource.AddSingleFile("models/condom/condom.sw.vtx")
	resource.AddSingleFile("models/condom/condom.vvd")
	resource.AddSingleFile("models/condom/condom.xbox.vtx")
	resource.AddSingleFile("sound/adultswep/Audrey_climax.wav")
	resource.AddSingleFile("sound/adultswep/Audrey1.wav")
	resource.AddSingleFile("sound/adultswep/Audrey2.wav")
	resource.AddSingleFile("sound/adultswep/Audrey3.wav")
	resource.AddSingleFile("sound/adultswep/Audrey4.wav")
	resource.AddSingleFile("sound/adultswep/Audrey5.wav")
	resource.AddSingleFile("sound/adultswep/Audrey6.wav")
	resource.AddSingleFile("sound/adultswep/Audrey7.wav")
	resource.AddSingleFile("sound/adultswep/Audrey8.wav")
	resource.AddSingleFile("sound/adultswep/Audrey9.wav")
	resource.AddSingleFile("sound/adultswep/Audrey10.wav")
	resource.AddSingleFile("sound/adultswep/Audrey11.wav")
	resource.AddSingleFile("sound/adultswep/Audrey12.wav")
	resource.AddSingleFile("sound/adultswep/Audrey13.wav")
	resource.AddSingleFile("sound/adultswep/Audrey14.wav")
	resource.AddSingleFile("sound/adultswep/Audrey15.wav")
	resource.AddSingleFile("sound/adultswep/Audrey16.wav")
	resource.AddSingleFile("sound/adultswep/Audrey17.wav")
	resource.AddSingleFile("sound/adultswep/Audrey18.wav")
	resource.AddSingleFile("sound/adultswep/sex1.wav")
	resource.AddSingleFile("sound/adultswep/sex2.wav")
	resource.AddSingleFile("sound/adultswep/sex3.wav")
	resource.AddSingleFile("sound/adultswep/sex4.wav")
	resource.AddSingleFile("sound/adultswep/sex5.wav")
	resource.AddSingleFile("sound/adultswep/sex6.wav")
	resource.AddSingleFile("sound/adultswep/sex7.wav")
	resource.AddSingleFile("sound/adultswep/sex8.wav")
	resource.AddSingleFile("sound/adultswep/sex9.wav")
	resource.AddSingleFile("sound/adultswep/sex10.wav")
	resource.AddSingleFile("sound/adultswep/sex11.wav")
	resource.AddSingleFile("sound/adultswep/sex12.wav")
	resource.AddSingleFile("sound/adultswep/sex13.wav")
	resource.AddSingleFile("sound/adultswep/suck01.wav")
	resource.AddSingleFile("sound/adultswep/suck02.wav")
	resource.AddSingleFile("sound/adultswep/suck03.wav")
	resource.AddSingleFile("sound/adultswep/suck04.wav")
	resource.AddSingleFile("sound/adultswep/suck05.wav")
	resource.AddSingleFile("sound/adultswep/suck06.wav")
	resource.AddSingleFile("sound/adultswep/suck07.wav")
	resource.AddSingleFile("sound/adultswep/suck08.wav")
	resource.AddSingleFile("sound/adultswep/suck09.wav")
	resource.AddSingleFile("sound/adultswep/suck10.wav")
	resource.AddSingleFile("sound/adultswep/suck11.wav")
	resource.AddSingleFile("sound/adultswep/suck12.wav")
	resource.AddSingleFile("sound/adultswep/suck13.wav")
	resource.AddSingleFile("sound/adultswep/suck14.wav")
	resource.AddSingleFile("sound/adultswep/suck15.wav")
	resource.AddSingleFile("sound/adultswep/suck16.wav")
	resource.AddSingleFile("sound/adultswep/suck17.wav")
	resource.AddSingleFile("sound/adultswep/suck18.wav")
	resource.AddSingleFile("sound/adultswep/suck19.wav")
	resource.AddSingleFile("sound/adultswep/suck20.wav")
	resource.AddSingleFile("sound/adultswep/suck21.wav")
	resource.AddSingleFile("sound/adultswep/suck22.wav")
	resource.AddSingleFile("sound/adultswep/suck23.wav")
	resource.AddSingleFile("sound/adultswep/suck24.wav")
	resource.AddSingleFile("sound/adultswep/Throat01.wav")
	resource.AddSingleFile("sound/adultswep/Throat02.wav")
	resource.AddSingleFile("sound/adultswep/Throat03.wav")
	resource.AddSingleFile("sound/adultswep/Throat04.wav")
	resource.AddSingleFile("sound/adultswep/Throat05.wav")

	resource.AddFile("materials/models/condom/condom_texture.vmt")
	resource.AddFile("materials/models/condom/condom_texture.vtf")
	resource.AddFile("models/condom/condom.dx80.vtx")
	resource.AddFile("models/condom/condom.dx90.vtx")
	resource.AddFile("models/condom/condom.mdl")
	resource.AddFile("models/condom/condom.phy")
	resource.AddFile("models/condom/condom.sw.vtx")
	resource.AddFile("models/condom/condom.vvd")
	resource.AddFile("models/condom/condom.xbox.vtx")
	resource.AddFile("sound/adultswep/Audrey_climax.wav")
	resource.AddFile("sound/adultswep/Audrey1.wav")
	resource.AddFile("sound/adultswep/Audrey2.wav")
	resource.AddFile("sound/adultswep/Audrey3.wav")
	resource.AddFile("sound/adultswep/Audrey4.wav")
	resource.AddFile("sound/adultswep/Audrey5.wav")
	resource.AddFile("sound/adultswep/Audrey6.wav")
	resource.AddFile("sound/adultswep/Audrey7.wav")
	resource.AddFile("sound/adultswep/Audrey8.wav")
	resource.AddFile("sound/adultswep/Audrey9.wav")
	resource.AddFile("sound/adultswep/Audrey10.wav")
	resource.AddFile("sound/adultswep/Audrey11.wav")
	resource.AddFile("sound/adultswep/Audrey12.wav")
	resource.AddFile("sound/adultswep/Audrey13.wav")
	resource.AddFile("sound/adultswep/Audrey14.wav")
	resource.AddFile("sound/adultswep/Audrey15.wav")
	resource.AddFile("sound/adultswep/Audrey16.wav")
	resource.AddFile("sound/adultswep/Audrey17.wav")
	resource.AddFile("sound/adultswep/Audrey18.wav")
	resource.AddFile("sound/adultswep/sex1.wav")
	resource.AddFile("sound/adultswep/sex2.wav")
	resource.AddFile("sound/adultswep/sex3.wav")
	resource.AddFile("sound/adultswep/sex4.wav")
	resource.AddFile("sound/adultswep/sex5.wav")
	resource.AddFile("sound/adultswep/sex6.wav")
	resource.AddFile("sound/adultswep/sex7.wav")
	resource.AddFile("sound/adultswep/sex8.wav")
	resource.AddFile("sound/adultswep/sex9.wav")
	resource.AddFile("sound/adultswep/sex10.wav")
	resource.AddFile("sound/adultswep/sex11.wav")
	resource.AddFile("sound/adultswep/sex12.wav")
	resource.AddFile("sound/adultswep/sex13.wav")
	resource.AddFile("sound/adultswep/suck01.wav")
	resource.AddFile("sound/adultswep/suck02.wav")
	resource.AddFile("sound/adultswep/suck03.wav")
	resource.AddFile("sound/adultswep/suck04.wav")
	resource.AddFile("sound/adultswep/suck05.wav")
	resource.AddFile("sound/adultswep/suck06.wav")
	resource.AddFile("sound/adultswep/suck07.wav")
	resource.AddFile("sound/adultswep/suck08.wav")
	resource.AddFile("sound/adultswep/suck09.wav")
	resource.AddFile("sound/adultswep/suck10.wav")
	resource.AddFile("sound/adultswep/suck11.wav")
	resource.AddFile("sound/adultswep/suck12.wav")
	resource.AddFile("sound/adultswep/suck13.wav")
	resource.AddFile("sound/adultswep/suck14.wav")
	resource.AddFile("sound/adultswep/suck15.wav")
	resource.AddFile("sound/adultswep/suck16.wav")
	resource.AddFile("sound/adultswep/suck17.wav")
	resource.AddFile("sound/adultswep/suck18.wav")
	resource.AddFile("sound/adultswep/suck19.wav")
	resource.AddFile("sound/adultswep/suck20.wav")
	resource.AddFile("sound/adultswep/suck21.wav")
	resource.AddFile("sound/adultswep/suck22.wav")
	resource.AddFile("sound/adultswep/suck23.wav")
	resource.AddFile("sound/adultswep/suck24.wav")
	resource.AddFile("sound/adultswep/Throat01.wav")
	resource.AddFile("sound/adultswep/Throat02.wav")
	resource.AddFile("sound/adultswep/Throat03.wav")
	resource.AddFile("sound/adultswep/Throat04.wav")
	resource.AddFile("sound/adultswep/Throat05.wav")

	ASWEP_VersionStatus = nil

	net.Receive( "AdultSwep_versioncheck", function( len, ply )
		net.Start("AdultSwep_versionresponse")
		net.WriteTable(ASWEP_VersionStatus or {})
		net.Send(ply)
	end )

	function AdultSwep_VersionCheck()
		-- make sure version checker only runs for people who've installed the mod.
		if file.Exists("sound/adultswep/Audrey_climax.wav", "GAME") then
			GitRC.CheckVersion("Kurome76", "Adult-SWEP", function(data)
				ASWEP_VersionStatus = 
				{
					IsLatest = data.uptodate,
					LatestDate = data.committime
				}
			end)
		end
	end

	hook.Add( "Initialize", "AdultSwep_versioncheck", function(move)
		util.AddNetworkString("AdultSwep_versioncheck")
		util.AddNetworkString("AdultSwep_versionresponse")
		
		timer.Simple(1, AdultSwep_VersionCheck)
	end )
else -- CLIENT
	net.Receive( "AdultSwep_versionresponse", function( len, ply )
		local response = net.ReadTable()
		local inDate = response.IsLatest
		local lastUpdate = response.LatestDate
		
		if inDate == nil then return end
		
		if !inDate then
			if lastUpdate then
				chat.AddText(Color(255,0,0), "A newer version of Adult SWEP is available! (last updated ", Color(255, 128, 0), os.date("%x", lastUpdate) , Color(255, 0, 0), ")")
			else
				chat.AddText(Color(255,0,0), "A newer version of Adult SWEP is available!")
			end
			
			chat.AddText(Color(255,0,0), "Update this server to the latest version at ", Color(255, 128, 0), "https://github.com/Bubbus/ACF-Missiles")
		else
			chat.AddText(Color(0,255,64), "Adult SWEP ", Color(0, 192, 42), "is up to date on this server!")
		end
	end )
	
	function AdultSwep_VersionCheck()
		net.Start("AdultSwep_versioncheck")
		net.SendToServer()
	end

	hook.Add( "CreateMove", "AdultSwep_versioncheck", function(move)
		if move:GetButtons() == 0 then return end
		
		hook.Remove("CreateMove", "AdultSwep_versioncheck")
		
		timer.Simple(1, AdultSwep_VersionCheck)
	end )
end